[env:arduino]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
extra_scripts = pre:gen_compile_commands.py
build_flags = -D CORE_DEBUG_LEVEL=4 -D LITTLEFS

board_upload.flash_size = 4MB
board_build.partitions = partition.csv
